### ISSUE TITLE
Configure file to download in config file

### ISSUE THREAD

**Issue by jaumebosch** [mente/MaxMindGeoIpBundle#5]
Would be nice to be able to specify which mmdb to download in the config.yml. Now is hardcoded to geolite2-country.mmdb

**Comment by mente** [comment]
Do you mean the one used by composer handler? Because for symfony command you're obliged to specify full url

**Comment by jaumebosch** [comment]
yep, that's it.
In my case I don't want to add to git the full db, I managerd to automatically launch a composer install after deploy and download the mmdb in that moment.

BTW, I possible can do the pull request during the week

**Comment by mente** [comment]
PR would be great :). Please keep in mind that in composer handler it's not that easy to get access to symfony app and probably you need to define url in `composer.json` extras

**Comment by jaumebosch** [comment]
you have a pull request, so quick and simply, but does the job

**Comment by jaumebosch** [comment]
:/ just modifing some path doesn't pass the travis test, but it should

**Comment by jaumebosch** [comment]
any clue?

**Comment by mente** [comment]
Check pull request, i gave comment there

**Comment by jaumebosch** [comment]
I'm unable to see any comment on the pull request :/

**Comment by mente** [comment]
https://github.com/mente/MaxMindGeoIpBundle/pull/6/files/c54dd15b07a1097b2489608d661552504df717e2#r99685167

**Comment by jaumebosch** [comment]
Man, I don't see any comment, in that link I just see my changes in the pull request

**Comment by mente** [comment]
Closed via #6
