### ISSUE TITLE
BC break on release 0.2.1

### ISSUE THREAD

**Issue by rvanlaak** [mente/MaxMindGeoIpBundle#7]
PR #6 is not BC and breaks the the library. It throws an `ErrorException` on `composer install` as it require devs to add `maxmind-db` to their options:

```
> Insomnia\MaxMindGeoIpBundle\Composer\ScriptHandler::downloadMaxMindDB
Script Insomnia\MaxMindGeoIpBundle\Composer\ScriptHandler::downloadMaxMindDB handling the symfony-scripts event terminated with an exception


  [ErrorException]
  Undefined index: maxmind-db

```

Where `ScriptHandler:23` checks whether `maxmind-db-path` isset, that does not happen for `maxmind-db` so the default fallback should have been provided. I will provide a PR to fix this.

**Comment by mente** [comment]
0.2.2 is just released
