### ISSUE TITLE
PHP Notice · Undefined index: country

### ISSUE THREAD

**Issue by janmyszkier** [mente/MaxMindGeoIpBundle#9]
there seems to be unhandled case in:
https://github.com/mente/MaxMindGeoIpBundle/blob/master/Service/GeoIpService.php#L48
where $res = $this->geoIp->get($ip); doesn't return correct country and causes that notice

**Comment by mente** [comment]
0.3.0 is released, it's not that breaking but as HHVM support is dropped, I've bumped the version
